[
{"title":"-","char":"Α","word":"α测试","index":"9-21"},
{"title":"-","char":"Β","word":"β测试","index":"9-21"},
{"title":"-","char":"4","word":"4+1 View","index":"6.2-17"},
{"title":"-","char":"4","word":"4+1 视图","index":"6.2-17"},
{"title":"-","char":"5","word":"5W1H","index":"10-13"},
{"title":"-","char":"A","word":"Abstraction","index":"4.2-16"},
{"title":"-","char":"A","word":"Action (State)","index":"6.2-80"},
{"title":"-","char":"A","word":"Activity (State)","index":"6.2-80"},
{"title":"-","char":"A","word":"Activity Diagram","index":"4.2-48"},
{"title":"-","char":"A","word":"Actor 定义","index":"4.2-33"},
{"title":"-","char":"A","word":"Actor 识别","index":"4.2-34"},
{"title":"-","char":"A","word":"Ada","index":"8-5"},
{"title":"-","char":"A","word":"Adaptable System","index":"5-39"},
{"title":"-","char":"A","word":"Aggregation","index":"4.2-87, 4.2-90, 4.2-98"},
{"title":"-","char":"A","word":"ALGO","index":"8-6"},
{"title":"-","char":"A","word":"Alpha测试","index":"9-21"},
{"title":"-","char":"A","word":"Alternative Flow","index":"4.2-41"},
{"title":"-","char":"A","word":"Analysis Class","index":"4.2-117"},
{"title":"-","char":"A","word":"APL","index":"8-6"},
{"title":"-","char":"A","word":"Application Layer","index":"6.2-25"},
{"title":"-","char":"A","word":"Architectural Layer","index":"6.2-21"},
{"title":"-","char":"A","word":"Architectural Patten","index":"5-37"},
{"title":"-","char":"A","word":"Assembler","index":"8-6"},
{"title":"-","char":"A","word":"Association","index":"4.2-79, 4.2-109"},
{"title":"-","char":"A","word":"Association Class","index":"6.2-86"},
{"title":"-","char":"A","word":"Attribute Representation","index":"6.2-84"},
{"title":"-","char":"A","word":"Awk","index":"8-8"},
{"title":"-","char":"B","word":"Baseline","index":"8-30"},
{"title":"-","char":"B","word":"Bash","index":"8-8"},
{"title":"-","char":"B","word":"BASIC","index":"8-6"},
{"title":"-","char":"B","word":"Basic Flow","index":"4.2-41"},
{"title":"-","char":"B","word":"Beta测试","index":"9-21"},
{"title":"-","char":"B","word":"Blackboard","index":"5-44"},
{"title":"-","char":"B","word":"Blackboard模式","index":"5-38"},
{"title":"-","char":"B","word":"Boundary Class","index":"4.2-121, 6.2-69"},
{"title":"-","char":"B","word":"BPR","index":"11-27"},
{"title":"-","char":"B","word":"Broker模式","index":"5-38"},
{"title":"-","char":"B","word":"Brooks 定律","index":"10-37"},
{"title":"-","char":"B","word":"Business Process Reengineering","index":"11-27"},
{"title":"-","char":"B","word":"Business Services Layer","index":"6.2-26"},
{"title":"-","char":"C","word":"C","index":"8-5"},
{"title":"-","char":"C","word":"C++","index":"8-5"},
{"title":"-","char":"C","word":"C/S 架构","index":"6.2-43"},
{"title":"-","char":"C","word":"Check - n","index":"8-33"},
{"title":"-","char":"C","word":"Check - t","index":"8-33"},
{"title":"-","char":"C","word":"Chief programmer team","index":"10-38"},
{"title":"-","char":"C","word":"CIM","index":"1-66, 2-35"},
{"title":"-","char":"C","word":"Class","index":"4.2-23, 6.2-6"},
{"title":"-","char":"C","word":"Class (Operation)","index":"4.2-139"},
{"title":"-","char":"C","word":"Class (Relationship)","index":"4.2-78, 4.2-139"},
{"title":"-","char":"C","word":"Class Diagram","index":"4.2-68"},
{"title":"-","char":"C","word":"Client/Server Architectures","index":"6.2-43"},
{"title":"-","char":"C","word":"CM Repository","index":"8-32"},
{"title":"-","char":"C","word":"COBOL","index":"8-6"},
{"title":"-","char":"C","word":"COCOMO","index":"10-31"},
{"title":"-","char":"C","word":"Code Documentation","index":"8-22"},
{"title":"-","char":"C","word":"Collaborate","index":"4.2-129"},
{"title":"-","char":"C","word":"Command Labeling","index":"7-33"},
{"title":"-","char":"C","word":"Communication Diagram","index":"4.2-136"},
{"title":"-","char":"C","word":"Communications - Association","index":"4.2-37"},
{"title":"-","char":"C","word":"Component","index":"6.2-50"},
{"title":"-","char":"C","word":"Component Diagram","index":"6.2-49"},
{"title":"-","char":"C","word":"Composition","index":"4.2-89, 4.2-90"},
{"title":"-","char":"C","word":"Conceptual Class","index":"4.2-72"},
{"title":"-","char":"C","word":"Conceptual Model","index":"4.2-71"},
{"title":"-","char":"C","word":"Connector","index":"6.2-45"},
{"title":"-","char":"C","word":"Control Class","index":"4.2-124, 6.2-71"},
{"title":"-","char":"C","word":"CSH","index":"8-8"},
{"title":"-","char":"D","word":"Data View","index":"6.2-52"},
{"title":"-","char":"D","word":"debugging","index":"9-3"},
{"title":"-","char":"D","word":"Defect density","index":"9-12"},
{"title":"-","char":"D","word":"Delegation","index":"4.2-103"},
{"title":"-","char":"D","word":"Democratic team","index":"10-38"},
{"title":"-","char":"D","word":"Dependency","index":"4.2-108"},
{"title":"-","char":"D","word":"Deployment View","index":"6.2-40"},
{"title":"-","char":"D","word":"Design Classes","index":"6.2-7"},
{"title":"-","char":"D","word":"Design Pattern","index":"5-37, 5-45"},
{"title":"-","char":"D","word":"Design Recovery","index":"11-24"},
{"title":"-","char":"D","word":"Design Reuse","index":"5-34"},
{"title":"-","char":"D","word":"Distributed System","index":"5-38"},
{"title":"-","char":"D","word":"Distribution Patterns","index":"6.2-42"},
{"title":"-","char":"E","word":"Eiffel","index":"8-5"},
{"title":"-","char":"E","word":"Encapsulation","index":"4.2-18"},
{"title":"-","char":"E","word":"Entity Class","index":"4.2-118, 6.2-72"},
{"title":"-","char":"E","word":"Error handling","index":"7-31"},
{"title":"-","char":"E","word":"Expected Result","index":"9-42"},
{"title":"-","char":"E","word":"Extend (Use-Case)","index":"4.2-59"},
{"title":"-","char":"F","word":"Façade Pattern","index":"5-47"},
{"title":"-","char":"F","word":"Factoring","index":"4.2-102"},
{"title":"-","char":"F","word":"Final State","index":"6.2-77"},
{"title":"-","char":"F","word":"Forth","index":"8-6"},
{"title":"-","char":"F","word":"FORTRAN","index":"8-5"},
{"title":"-","char":"F","word":"Forward Engineering","index":"6.2-87, 8-24"},
{"title":"-","char":"F","word":"Framework","index":"5-49"},
{"title":"-","char":"F","word":"Functionality","index":"3-7"},
{"title":"-","char":"F","word":"FURPS","index":"3-8"},
{"title":"-","char":"G","word":"Gang of Four","index":"5-46"},
{"title":"-","char":"G","word":"Generalization (Actor)","index":"4.2-65"},
{"title":"-","char":"G","word":"Generalization (Class)","index":"4.2-89"},
{"title":"-","char":"G","word":"Generalization (Use-Case)","index":"4.2-63"},
{"title":"-","char":"G","word":"GoF","index":"5-46"},
{"title":"-","char":"G","word":"GOTO 语句","index":"8-19"},
{"title":"-","char":"G","word":"Graphics User Interface","index":"7-15"},
{"title":"-","char":"G","word":"GUI","index":"7-15"},
{"title":"-","char":"H","word":"Haskell","index":"8-5"},
{"title":"-","char":"H","word":"Help facility","index":"7-28"},
{"title":"-","char":"H","word":"Hierarchical team","index":"10-38"},
{"title":"-","char":"H","word":"Hierarchy","index":"4.2-22"},
{"title":"-","char":"I","word":"Id","index":"8-5"},
{"title":"-","char":"I","word":"Idiom","index":"5-37"},
{"title":"-","char":"I","word":"Implementation Inheritance","index":"4.2-104"},
{"title":"-","char":"I","word":"Implementation View","index":"6.2-48"},
{"title":"-","char":"I","word":"Include (Use-Case)","index":"4.2-57"},
{"title":"-","char":"I","word":"Inherit","index":"4.2-96"},
{"title":"-","char":"I","word":"Initial State","index":"6.2-77"},
{"title":"-","char":"I","word":"Interaction Diagram","index":"4.2-131"},
{"title":"-","char":"I","word":"Interactive System","index":"5-39"},
{"title":"-","char":"I","word":"Interface","index":"6.2-9"},
{"title":"-","char":"I","word":"Internationalization","index":"7-37"},
{"title":"-","char":"I","word":"IT黑洞","index":"3-26"},
{"title":"-","char":"J","word":"J2EE","index":"5-53"},
{"title":"-","char":"J","word":"Java","index":"8-5"},
{"title":"-","char":"J","word":"JavaScript","index":"8-10"},
{"title":"-","char":"J","word":"JDBC","index":"6.2-31"},
{"title":"-","char":"J","word":"JSF","index":"5-55"},
{"title":"-","char":"J","word":"JSP Model II","index":"5-52"},
{"title":"-","char":"L","word":"Layered Architecture","index":"5-41"},
{"title":"-","char":"L","word":"Layering Approach","index":"6.2-20"},
{"title":"-","char":"L","word":"Layers模式","index":"5-38"},
{"title":"-","char":"L","word":"Liskov替换原则","index":"4.2-105"},
{"title":"-","char":"L","word":"LISP","index":"8-5"},
{"title":"-","char":"L","word":"Logical View","index":"6.2-18"},
{"title":"-","char":"L","word":"LSP","index":"4.2-105"},
{"title":"-","char":"M","word":"Menu","index":"7-33"},
{"title":"-","char":"M","word":"Messages","index":"4.2-130"},
{"title":"-","char":"M","word":"Microkernel","index":"5-39"},
{"title":"-","char":"M","word":"ML","index":"8-5"},
{"title":"-","char":"M","word":"Model - View - Controller","index":"5-39"},
{"title":"-","char":"M","word":"Modula","index":"8-6"},
{"title":"-","char":"M","word":"Modularity","index":"4.2-20"},
{"title":"-","char":"M","word":"Multimodal User Interface","index":"7-17"},
{"title":"-","char":"M","word":"Multiple Inheritance","index":"4.2-95"},
{"title":"-","char":"M","word":"Multiplicity","index":"4.2-80"},
{"title":"-","char":"M","word":"MVC","index":"5-39, 5-40"},
{"title":"-","char":"M","word":"MVC框架","index":"5-50"},
{"title":"-","char":"N","word":"Navigability","index":"4.2-85"},
{"title":"-","char":"N","word":"Node (Deployment View)","index":"6.2-44"},
{"title":"-","char":"O","word":"Object - orientation","index":"4.2-7"},
{"title":"-","char":"O","word":"Object Technology","index":"4.2-3"},
{"title":"-","char":"O","word":"OO","index":"4.2-7"},
{"title":"-","char":"O","word":"Operation (Class)","index":"4.2-139"},
{"title":"-","char":"O","word":"Operation Signature","index":"6.2-73"},
{"title":"-","char":"O","word":"OR Mapping","index":"6.2-55"},
{"title":"-","char":"O","word":"ORM框架","index":"5-50"},
{"title":"-","char":"O","word":"OR映射","index":"6.2-55"},
{"title":"-","char":"P","word":"PAC","index":"5-39"},
{"title":"-","char":"P","word":"Package","index":"4.2-26, 6.2-11"},
{"title":"-","char":"P","word":"Partitioning","index":"6.2-23"},
{"title":"-","char":"P","word":"Partitions","index":"4.2-50"},
{"title":"-","char":"P","word":"Performance","index":"3-11"},
{"title":"-","char":"P","word":"Perl","index":"8-9"},
{"title":"-","char":"P","word":"Persistence Design Pattern","index":"6.2-30"},
{"title":"-","char":"P","word":"PHP","index":"8-9"},
{"title":"-","char":"P","word":"PIM","index":"1-66, 2-35, 3-45"},
{"title":"-","char":"P","word":"Pipes and Filters","index":"5-43"},
{"title":"-","char":"P","word":"PL/I","index":"8-6"},
{"title":"-","char":"P","word":"PMBOK","index":"10-6, 10-12"},
{"title":"-","char":"P","word":"Presentation - abstraction - control ","index":"5-39"},
{"title":"-","char":"P","word":"Process","index":"6.2-38"},
{"title":"-","char":"P","word":"Process View","index":"6.2-37"},
{"title":"-","char":"P","word":"Prolog","index":"8-5"},
{"title":"-","char":"P","word":"PSM","index":"1-66, 2-35"},
{"title":"-","char":"P","word":"Python","index":"8-10"},
{"title":"-","char":"R","word":"Rayleigh - n曲线","index":"10-36"},
{"title":"-","char":"R","word":"Reengineering","index":"11-25"},
{"title":"-","char":"R","word":"Refactoring","index":"5-32, 11-24"},
{"title":"-","char":"R","word":"Relational Data Model","index":"6.2-53"},
{"title":"-","char":"R","word":"Relationship (Class)","index":"4.2-78, 4.2-139"},
{"title":"-","char":"R","word":"Reliability","index":"3-9"},
{"title":"-","char":"R","word":"Response time","index":"7-27"},
{"title":"-","char":"R","word":"Restructuring","index":"11-24"},
{"title":"-","char":"R","word":"Reuse","index":"5-34"},
{"title":"-","char":"R","word":"Reverse Engineering","index":"6.2-87, 8-24, 11-24"},
{"title":"-","char":"R","word":"Role (Class Diagram)","index":"4.2-84"},
{"title":"-","char":"R","word":"Round - p Engineering","index":"6.2-87, 8-24"},
{"title":"-","char":"R","word":"Ruby","index":"8-11"},
{"title":"-","char":"R","word":"RUP","index":"2-37"},
{"title":"-","char":"S","word":"Sandwich testing","index":"9-16"},
{"title":"-","char":"S","word":"Scenario","index":"4.2-43"},
{"title":"-","char":"S","word":"Scheme","index":"8-5"},
{"title":"-","char":"S","word":"Script Language","index":"8-7"},
{"title":"-","char":"S","word":"Sequence Diagram","index":"4.2-133"},
{"title":"-","char":"S","word":"Shell","index":"8-8"},
{"title":"-","char":"S","word":"Significant State","index":"6.2-83"},
{"title":"-","char":"S","word":"Single Inheritance","index":"4.2-94"},
{"title":"-","char":"S","word":"Smalltalk","index":"8-5"},
{"title":"-","char":"S","word":"SNOBOL","index":"8-6"},
{"title":"-","char":"S","word":"Software Evolution","index":"11-5"},
{"title":"-","char":"S","word":"Software Maintenance","index":"11-5"},
{"title":"-","char":"S","word":"Special State","index":"6.2-77"},
{"title":"-","char":"S","word":"Spreedsheets","index":"8-5"},
{"title":"-","char":"S","word":"SRS","index":"3-50"},
{"title":"-","char":"S","word":"SRS模板","index":"3-63"},
{"title":"-","char":"S","word":"State","index":"6.2-75"},
{"title":"-","char":"S","word":"State Machine Diagram","index":"6.2-76"},
{"title":"-","char":"S","word":"Struts","index":"5-54"},
{"title":"-","char":"S","word":"Subsystem","index":"6.2-9"},
{"title":"-","char":"S","word":"Subsystem Interactions","index":"6.2-63"},
{"title":"-","char":"S","word":"Supportability","index":"3-10"},
{"title":"-","char":"S","word":"SWEBOK","index":"1-37"},
{"title":"-","char":"T","word":"Tcl","index":"8-10"},
{"title":"-","char":"T","word":"Test Case","index":"9-42"},
{"title":"-","char":"T","word":"Test Factor","index":"9-41"},
{"title":"-","char":"T","word":"Test Input","index":"9-42"},
{"title":"-","char":"T","word":"testing","index":"9-1"},
{"title":"-","char":"T","word":"Thread","index":"6.2-38"},
{"title":"-","char":"U","word":"UI类","index":"6.2-69"},
{"title":"-","char":"U","word":"UML对象表达","index":"4.2-14"},
{"title":"-","char":"U","word":"UML建模工具","index":"1-75"},
{"title":"-","char":"U","word":"UML类表达","index":"4.2-24"},
{"title":"-","char":"U","word":"UML历史","index":"4.2-8"},
{"title":"-","char":"U","word":"UML模型","index":"1-74"},
{"title":"-","char":"U","word":"UML软件模型视图","index":"1-65"},
{"title":"-","char":"U","word":"URPS","index":"3-8"},
{"title":"-","char":"U","word":"Usability","index":"3-12"},
{"title":"-","char":"U","word":"Use - Case","index":"4.2-29"},
{"title":"-","char":"U","word":"Use - Case Specification","index":"4.2-40"},
{"title":"-","char":"U","word":"Use - Case 技术","index":"4.2-29"},
{"title":"-","char":"U","word":"Use - Case建模步骤","index":"4.2-31, 4.2-31"},
{"title":"-","char":"U","word":"Use - Case间的关系","index":"4.2-55"},
{"title":"-","char":"U","word":"Use - Case技术SRS模板","index":"3-64"},
{"title":"-","char":"U","word":"Use - Case模型组成","index":"4.2-30"},
{"title":"-","char":"U","word":"Use - Case识别","index":"4.2-34"},
{"title":"-","char":"U","word":"Use - case图","index":"4.2-53"},
{"title":"-","char":"U","word":"Use - e Realization","index":"4.2-116"},
{"title":"-","char":"V","word":"Val","index":"8-5"},
{"title":"-","char":"V","word":"Version","index":"8-29"},
{"title":"-","char":"V","word":"Visibility","index":"4.2-110"},
{"title":"-","char":"V","word":"Vision","index":"3-29, 3-50"},
{"title":"-","char":"W","word":"WBS","index":"10-28"},
{"title":"-","char":"W","word":"Web页面建模","index":"6.2-70"},
{"title":"-","char":"X","word":"XSLT","index":"8-5"},
{"title":"-","char":"Y","word":"Yes... But现象","index":"3-26"},
{"title":"A","char":"安","word":"安全性","index":"5-9"},
{"title":"B","char":"白","word":"白盒测试","index":"9-26"},
{"title":"B","char":"版","word":"版本","index":"8-29"},
{"title":"B","char":"版","word":"版本控制","index":"8-31"},
{"title":"B","char":"包","word":"包","index":"6.2-11"},
{"title":"B","char":"包","word":"包定义","index":"4.2-26"},
{"title":"B","char":"包","word":"包含 (用例)","index":"4.2-57"},
{"title":"B","char":"备","word":"备选流","index":"4.2-41"},
{"title":"B","char":"变","word":"变更控制程序","index":"3-71"},
{"title":"B","char":"编","word":"编程","index":"1-44"},
{"title":"B","char":"编","word":"编程的误区","index":"1-45"},
{"title":"B","char":"编","word":"编码的风格","index":"8-18"},
{"title":"B","char":"编","word":"编码准则","index":"8-15"},
{"title":"B","char":"边","word":"边界类","index":"4.2-121, 6.2-69"},
{"title":"B","char":"并","word":"并行开发","index":"8-34"},
{"title":"B","char":"波","word":"波音747","index":"1-56"},
{"title":"B","char":"布","word":"布局","index":"7-34"},
{"title":"B","char":"布","word":"布鲁克斯定律","index":"10-37"},
{"title":"B","char":"部","word":"部署","index":"1-47"},
{"title":"B","char":"部","word":"部署视图","index":"6.2-40"},
{"title":"C","char":"菜","word":"菜单","index":"7-33"},
{"title":"C","char":"采","word":"采购管理","index":"10-10"},
{"title":"C","char":"参","word":"参与者 定义","index":"4.2-33"},
{"title":"C","char":"参","word":"参与者 识别","index":"4.2-34"},
{"title":"C","char":"操","word":"操作 (类)","index":"4.2-139"},
{"title":"C","char":"操","word":"操作签名","index":"6.2-73"},
{"title":"C","char":"操","word":"操作信息反馈","index":"7-29"},
{"title":"C","char":"层","word":"层次架构风格","index":"5-41"},
{"title":"C","char":"层","word":"层次型组织结构","index":"10-38"},
{"title":"C","char":"测","word":"测试","index":"1-46, 9-1"},
{"title":"C","char":"测","word":"测试 生命周期","index":"9-7"},
{"title":"C","char":"测","word":"测试覆盖","index":"9-26"},
{"title":"C","char":"测","word":"测试过程","index":"9-39"},
{"title":"C","char":"测","word":"测试技术","index":"9-25"},
{"title":"C","char":"测","word":"测试计划","index":"9-40"},
{"title":"C","char":"测","word":"测试目的","index":"9-3"},
{"title":"C","char":"测","word":"测试驱动开发","index":"9-2"},
{"title":"C","char":"测","word":"测试输入","index":"9-42"},
{"title":"C","char":"测","word":"测试因素","index":"9-41"},
{"title":"C","char":"测","word":"测试用例","index":"9-42"},
{"title":"C","char":"测","word":"测试终止","index":"9-45"},
{"title":"C","char":"测","word":"测试准则","index":"9-4"},
{"title":"C","char":"测","word":"测试自动化","index":"9-7"},
{"title":"C","char":"测","word":"测试组","index":"9-5"},
{"title":"C","char":"唱","word":"唱片播放器","index":"6.2-79"},
{"title":"C","char":"常","word":"常用术语","index":"3-35"},
{"title":"C","char":"产","word":"产品定位","index":"3-52"},
{"title":"C","char":"产","word":"产品特性","index":"3-53"},
{"title":"C","char":"产","word":"产业现状","index":"1-19"},
{"title":"C","char":"成","word":"成本管理","index":"10-9"},
{"title":"C","char":"成","word":"成功的标准","index":"10-8"},
{"title":"C","char":"成","word":"成功率","index":"1-16"},
{"title":"C","char":"成","word":"成例","index":"5-37"},
{"title":"C","char":"持","word":"持久设计模式","index":"6.2-30"},
{"title":"C","char":"重","word":"重构","index":"5-32, 11-24"},
{"title":"C","char":"重","word":"重用","index":"5-34"},
{"title":"C","char":"抽","word":"抽象","index":"4.2-16"},
{"title":"C","char":"抽","word":"抽象 (设计)","index":"5-15"},
{"title":"C","char":"传","word":"传统技术SRS模板","index":"3-63"},
{"title":"C","char":"出","word":"出错处理","index":"7-31"},
{"title":"C","char":"初","word":"初始状态","index":"6.2-77"},
{"title":"C","char":"初","word":"初学型","index":"7-23"},
{"title":"D","char":"单","word":"单继承","index":"4.2-94"},
{"title":"D","char":"单","word":"单元测试","index":"9-9"},
{"title":"D","char":"导","word":"导览","index":"4.2-85"},
{"title":"D","char":"迭","word":"迭代","index":"2-39"},
{"title":"D","char":"定","word":"定义","index":"1-30"},
{"title":"D","char":"定","word":"定制软件","index":"1-5"},
{"title":"D","char":"动","word":"动作 (状态机图)","index":"6.2-80"},
{"title":"D","char":"对","word":"对象-类关系","index":"4.2-25"},
{"title":"D","char":"对","word":"对象表达UML","index":"4.2-14"},
{"title":"D","char":"对","word":"对象层次","index":"4.2-22"},
{"title":"D","char":"对","word":"对象定义","index":"4.2-12"},
{"title":"D","char":"对","word":"对象技术","index":"4.2-3"},
{"title":"D","char":"多","word":"多重度","index":"4.2-80"},
{"title":"D","char":"多","word":"多继承","index":"4.2-95"},
{"title":"D","char":"多","word":"多媒体用户界面","index":"7-16"},
{"title":"D","char":"多","word":"多通道用户界面","index":"7-17"},
{"title":"E","char":"二","word":"二义性","index":"3-18"},
{"title":"F","char":"方","word":"方案","index":"4.2-43"},
{"title":"F","char":"防","word":"防错处理","index":"7-32"},
{"title":"F","char":"反","word":"反馈操作信息","index":"7-29"},
{"title":"F","char":"泛","word":"泛化 (参与者)","index":"4.2-65"},
{"title":"F","char":"泛","word":"泛化 (类)","index":"4.2-89"},
{"title":"F","char":"泛","word":"泛化 (类的关系)","index":"4.2-"},
{"title":"F","char":"泛","word":"泛化 (用例)","index":"4.2-63"},
{"title":"F","char":"范","word":"范围管理","index":"10-9"},
{"title":"F","char":"发","word":"发展","index":"1-52"},
{"title":"F","char":"费","word":"费用分配比例","index":"1-50"},
{"title":"F","char":"费","word":"费用管理","index":"10-7"},
{"title":"F","char":"非","word":"非功能需求","index":"3-8"},
{"title":"F","char":"冯","word":"冯诺依曼语言","index":"8-5"},
{"title":"F","char":"封","word":"封装","index":"4.2-18"},
{"title":"F","char":"风","word":"风格 (界面)","index":"7-13"},
{"title":"F","char":"风","word":"风险管理","index":"10-10"},
{"title":"F","char":"风","word":"风险驱动","index":"2-37"},
{"title":"F","char":"分","word":"分布模式","index":"6.2-42"},
{"title":"F","char":"分","word":"分布式系统","index":"5-38"},
{"title":"F","char":"分","word":"分层","index":"6.2-20"},
{"title":"F","char":"分","word":"分层模式","index":"5-38"},
{"title":"F","char":"分","word":"分工","index":"10-35"},
{"title":"F","char":"分","word":"分解","index":"4.2-102, 5-20"},
{"title":"F","char":"分","word":"分配比例","index":"1-48, 1-50"},
{"title":"F","char":"分","word":"分析建模准则","index":"3-44"},
{"title":"F","char":"分","word":"分析类","index":"4.2-117"},
{"title":"F","char":"分","word":"分析模型","index":"3-45, 6.2-3"},
{"title":"F","char":"复","word":"复合框架","index":"5-50"},
{"title":"F","char":"复","word":"复用","index":"5-34"},
{"title":"F","char":"复","word":"复杂性","index":"1-35"},
{"title":"F","char":"服","word":"服务对象 (界面)","index":"7-5"},
{"title":"F","char":"覆","word":"覆盖 (测试)","index":"9-26"},
{"title":"G","char":"概","word":"概念类","index":"4.2-72"},
{"title":"G","char":"概","word":"概念模型","index":"4.2-71"},
{"title":"G","char":"概","word":"概要需求","index":"3-50"},
{"title":"G","char":"杠","word":"杠杆作用点","index":"2-4"},
{"title":"G","char":"高","word":"高级程序设计语言","index":"8-5"},
{"title":"G","char":"功","word":"功能需求","index":"3-7"},
{"title":"G","char":"工","word":"工程定义","index":"1-27"},
{"title":"G","char":"工","word":"工作量分配比例","index":"1-48"},
{"title":"G","char":"工","word":"工作细化结构","index":"10-28"},
{"title":"G","char":"构","word":"构件","index":"2-28, 6.2-50"},
{"title":"G","char":"构","word":"构件级设计","index":"5-13, 6.2-57"},
{"title":"G","char":"构","word":"构件图","index":"6.2-49"},
{"title":"G","char":"沟","word":"沟通管理","index":"10-10"},
{"title":"G","char":"关","word":"关键状态","index":"6.2-83"},
{"title":"G","char":"关","word":"关联关系","index":"4.2-79, 4.2-109"},
{"title":"G","char":"关","word":"关联类","index":"6.2-86"},
{"title":"G","char":"关","word":"关系 (类)","index":"4.2-78, 4.2-139"},
{"title":"G","char":"关","word":"关系 (用例)","index":"4.2-55"},
{"title":"G","char":"关","word":"关系数据模型","index":"6.2-53"},
{"title":"G","char":"管","word":"管道和过滤器风格","index":"5-43"},
{"title":"G","char":"管","word":"管理过程","index":"10-12"},
{"title":"G","char":"管","word":"管理活动","index":"1-39"},
{"title":"G","char":"管","word":"管理人员的误区","index":"1-22"},
{"title":"G","char":"国","word":"国际化","index":"7-37"},
{"title":"G","char":"过","word":"过程抽象","index":"5-17"},
{"title":"G","char":"估","word":"估算","index":"10-30"},
{"title":"G","char":"故","word":"故障曲线","index":"1-7"},
{"title":"H","char":"函","word":"函数式语言","index":"8-5"},
{"title":"H","char":"黑","word":"黑板风格","index":"5-44"},
{"title":"H","char":"黑","word":"黑板模式","index":"5-38"},
{"title":"H","char":"黑","word":"黑盒测试","index":"9-18, 9-34"},
{"title":"H","char":"合","word":"合成关系","index":"4.2-89, 4.2-90"},
{"title":"H","char":"合","word":"合同项目的立项管理","index":"10-23"},
{"title":"H","char":"核","word":"核心开发计划","index":"10-27"},
{"title":"H","char":"核","word":"核心准则","index":"1-34"},
{"title":"H","char":"后","word":"后置条件","index":"4.2-52"},
{"title":"H","char":"黄","word":"黄金规则 (界面)","index":"7-7"},
{"title":"H","char":"回","word":"回归测试","index":"9-37"},
{"title":"H","char":"混","word":"混合方式测试","index":"9-16"},
{"title":"H","char":"活","word":"活动","index":"1-39"},
{"title":"H","char":"活","word":"活动 (状态机图)","index":"6.2-80"},
{"title":"H","char":"活","word":"活动图","index":"4.2-48, 4.2-53"},
{"title":"J","char":"建","word":"建模","index":"1-62"},
{"title":"J","char":"建","word":"建模Web页面","index":"6.2-70"},
{"title":"J","char":"建","word":"建模的方法","index":"1-68"},
{"title":"J","char":"建","word":"建模的重要性","index":"1-62"},
{"title":"J","char":"检","word":"检出","index":"8-33"},
{"title":"J","char":"检","word":"检入","index":"8-33"},
{"title":"J","char":"监","word":"监控 (项目)","index":"10-45"},
{"title":"J","char":"交","word":"交互图","index":"4.2-53, 4.2-131"},
{"title":"J","char":"交","word":"交互系统","index":"5-39"},
{"title":"J","char":"教","word":"教育 (界面)","index":"7-5"},
{"title":"J","char":"脚","word":"脚本语言","index":"8-7"},
{"title":"J","char":"角","word":"角色 (类图)","index":"4.2-84"},
{"title":"J","char":"架","word":"架构风格","index":"5-7, 5-38, 6.2-19"},
{"title":"J","char":"架","word":"架构模式","index":"5-37"},
{"title":"J","char":"架","word":"架构设计","index":"5-7"},
{"title":"J","char":"驾","word":"驾驭软件 (界面)","index":"7-8"},
{"title":"J","char":"接","word":"接口","index":"6.2-9"},
{"title":"J","char":"接","word":"接口设计","index":"3-61, 5-12"},
{"title":"J","char":"界","word":"界面框架","index":"5-50"},
{"title":"J","char":"界","word":"界面设计 典型错误","index":"7-3"},
{"title":"J","char":"界","word":"界面设计 黄金规则","index":"7-7"},
{"title":"J","char":"界","word":"界面设计风格","index":"7-13"},
{"title":"J","char":"界","word":"界面设计过程","index":"7-22"},
{"title":"J","char":"界","word":"界面设计模式","index":"7-18"},
{"title":"J","char":"界","word":"界面设计模型","index":"7-21"},
{"title":"J","char":"界","word":"界面设计要素","index":"7-26"},
{"title":"J","char":"结","word":"结构 (团队)","index":"10-35"},
{"title":"J","char":"结","word":"结构化的分析模型","index":"3-46"},
{"title":"J","char":"结","word":"结构化方法","index":"1-72"},
{"title":"J","char":"节","word":"节点 (部署视图)","index":"6.2-44"},
{"title":"J","char":"解","word":"解决方案","index":"3-27"},
{"title":"J","char":"阶","word":"阶段","index":"2-38"},
{"title":"J","char":"净","word":"净室软件工程","index":"2-30"},
{"title":"J","char":"竞","word":"竞赛","index":"8-26, 8-"},
{"title":"J","char":"经","word":"经验教训","index":"10-51"},
{"title":"J","char":"经","word":"经验模型","index":"10-31"},
{"title":"J","char":"经","word":"经验模型 (估算)","index":"10-31"},
{"title":"J","char":"进","word":"进程","index":"6.2-38"},
{"title":"J","char":"金","word":"金三角","index":"1-38"},
{"title":"J","char":"纠","word":"纠错性维护","index":"1-51"},
{"title":"J","char":"基","word":"基本流","index":"4.2-41"},
{"title":"J","char":"基","word":"基线","index":"8-30"},
{"title":"J","char":"基","word":"基于构件的开发","index":"2-29"},
{"title":"J","char":"基","word":"基于构件组装","index":"1-5"},
{"title":"J","char":"基","word":"基于约束的语言","index":"8-5"},
{"title":"J","char":"技","word":"技术活动","index":"1-39"},
{"title":"J","char":"技","word":"技术实现 (界面)","index":"7-2"},
{"title":"J","char":"继","word":"继承","index":"4.2-96"},
{"title":"J","char":"继","word":"继承 实现","index":"4.2-104"},
{"title":"J","char":"计","word":"计算无关模型","index":"1-66, 2-35"},
{"title":"J","char":"记","word":"记忆 (界面)","index":"7-9"},
{"title":"J","char":"集","word":"集成测试","index":"9-14"},
{"title":"J","char":"集","word":"集成管理","index":"10-10"},
{"title":"J","char":"聚","word":"聚合关系","index":"4.2-87, 4.2-90, 4.2-98"},
{"title":"K","char":"开","word":"开发人员的误区","index":"1-24"},
{"title":"K","char":"可","word":"可测试性","index":"5-9, 11-18"},
{"title":"K","char":"可","word":"可见度","index":"4.2-110"},
{"title":"K","char":"可","word":"可靠性","index":"3-9, 5-8"},
{"title":"K","char":"可","word":"可理解性","index":"3-20, 11-17"},
{"title":"K","char":"可","word":"可维护性","index":"5-9, 11-16"},
{"title":"K","char":"可","word":"可修改性","index":"11-19"},
{"title":"K","char":"可","word":"可验证性","index":"3-21, 3-21"},
{"title":"K","char":"可","word":"可移植性","index":"11-20"},
{"title":"K","char":"可","word":"可用性","index":"3-12, 5-8"},
{"title":"K","char":"客","word":"客户的误区","index":"1-23"},
{"title":"K","char":"控","word":"控制复杂性","index":"1-35"},
{"title":"K","char":"控","word":"控制类","index":"4.2-124, 6.2-71"},
{"title":"K","char":"快","word":"快速原型模型","index":"2-21"},
{"title":"K","char":"框","word":"框架","index":"5-49"},
{"title":"K","char":"扩","word":"扩展 (用例)","index":"4.2-59"},
{"title":"K","char":"扩","word":"扩展点","index":"4.2-53"},
{"title":"L","char":"类","word":"类","index":"6.2-6"},
{"title":"L","char":"类","word":"类 操作","index":"4.2-139"},
{"title":"L","char":"类","word":"类 关系","index":"4.2-78, 4.2-139"},
{"title":"L","char":"类","word":"类-对象关系","index":"4.2-25"},
{"title":"L","char":"类","word":"类表达UML","index":"4.2-24"},
{"title":"L","char":"类","word":"类定义","index":"4.2-23"},
{"title":"L","char":"类","word":"类设计","index":"5-6"},
{"title":"L","char":"类","word":"类图","index":"4.2-68"},
{"title":"L","char":"良","word":"良好的工程","index":"1-28"},
{"title":"L","char":"联","word":"联结器","index":"6.2-45"},
{"title":"L","char":"六","word":"六拍项目","index":"10-14"},
{"title":"L","char":"立","word":"立项管理","index":"10-16"},
{"title":"L","char":"螺","word":"螺旋模型","index":"2-24"},
{"title":"L","char":"逻","word":"逻辑式语言","index":"8-5"},
{"title":"L","char":"逻","word":"逻辑视图","index":"6.2-18"},
{"title":"M","char":"冒","word":"冒烟测试","index":"9-36"},
{"title":"M","char":"面","word":"面向对象","index":"4.2-9"},
{"title":"M","char":"面","word":"面向对象步骤","index":"4.2-9"},
{"title":"M","char":"面","word":"面向对象的分析模型","index":"3-47"},
{"title":"M","char":"面","word":"面向对象的基本原则","index":"4.2-15"},
{"title":"M","char":"面","word":"面向对象方法","index":"1-73"},
{"title":"M","char":"面","word":"面向对象分析","index":"4.2-7"},
{"title":"M","char":"面","word":"面向对象设计","index":"6.2-4"},
{"title":"M","char":"面","word":"面向对象语言","index":"8-5"},
{"title":"M","char":"面","word":"面向方面软件开发","index":"2-33"},
{"title":"M","char":"描","word":"描述用户界面","index":"3-62"},
{"title":"M","char":"命","word":"命令标记","index":"7-33"},
{"title":"M","char":"命","word":"命令式语言","index":"8-5"},
{"title":"M","char":"民","word":"民主开发小组","index":"10-38"},
{"title":"M","char":"模","word":"模板 (语言)","index":"8-5"},
{"title":"M","char":"模","word":"模块的优劣标准","index":"5-27"},
{"title":"M","char":"模","word":"模块独立","index":"5-23"},
{"title":"M","char":"模","word":"模块化","index":"4.2-20, 5-19"},
{"title":"M","char":"模","word":"模式","index":"5-35"},
{"title":"M","char":"模","word":"模型","index":"1-59"},
{"title":"M","char":"模","word":"模型 (界面)","index":"7-21"},
{"title":"M","char":"模","word":"模型的定义","index":"1-59"},
{"title":"M","char":"模","word":"模型的多个视图","index":"1-64"},
{"title":"M","char":"模","word":"模型的功能","index":"1-61"},
{"title":"M","char":"模","word":"模型的特征","index":"1-63"},
{"title":"M","char":"模","word":"模型的转换","index":"1-67"},
{"title":"M","char":"模","word":"模型驱动开发","index":"2-27"},
{"title":"M","char":"磨","word":"磨损","index":"1-5"},
{"title":"N","char":"内","word":"内聚 (定义)","index":"5-24"},
{"title":"N","char":"内","word":"内聚 (级别)","index":"5-25"},
{"title":"N","char":"逆","word":"逆向工程","index":"6.2-87, 8-24, 11-24"},
{"title":"O","char":"耦","word":"耦合 (定义)","index":"5-24"},
{"title":"O","char":"耦","word":"耦合 (级别)","index":"5-26"},
{"title":"P","char":"配","word":"配置复查","index":"9-19"},
{"title":"P","char":"配","word":"配置库","index":"8-32"},
{"title":"P","char":"喷","word":"喷泉模型","index":"2-25"},
{"title":"P","char":"平","word":"平台无关模型","index":"1-66, 2-35, 3-45"},
{"title":"P","char":"评","word":"评审方法","index":"3-66"},
{"title":"P","char":"瀑","word":"瀑布型","index":"2-10"},
{"title":"Q","char":"前","word":"前景文档","index":"3-29, 3-51"},
{"title":"Q","char":"前","word":"前置条件","index":"4.2-51"},
{"title":"Q","char":"求","word":"求助设施","index":"7-28"},
{"title":"Q","char":"启","word":"启动项目","index":"10-15"},
{"title":"Q","char":"期","word":"期望结果","index":"9-42"},
{"title":"Q","char":"确","word":"确认测试","index":"9-17"},
{"title":"Q","char":"缺","word":"缺陷报告","index":"9-43"},
{"title":"Q","char":"缺","word":"缺陷密度","index":"9-12"},
{"title":"R","char":"人","word":"人力资源管理","index":"10-9"},
{"title":"R","char":"人","word":"人员时间权衡定律","index":"10-37"},
{"title":"R","char":"人","word":"人员组织","index":"10-38"},
{"title":"R","char":"软","word":"软件产业现状","index":"1-19"},
{"title":"R","char":"软","word":"软件的定义","index":"1-4"},
{"title":"R","char":"软","word":"软件的分类","index":"1-10"},
{"title":"R","char":"软","word":"软件的特征","index":"1-5"},
{"title":"R","char":"软","word":"软件复杂性","index":"1-13"},
{"title":"R","char":"软","word":"软件工程定义","index":"1-30"},
{"title":"R","char":"软","word":"软件工程核心准则","index":"1-34"},
{"title":"R","char":"软","word":"软件工程战略性学科","index":"1-33"},
{"title":"R","char":"软","word":"软件过程","index":"2-5"},
{"title":"R","char":"软","word":"软件过程的杠杆作用点","index":"2-4"},
{"title":"R","char":"软","word":"软件过程知识体系","index":"1-37"},
{"title":"R","char":"软","word":"软件过程组成","index":"2-6"},
{"title":"R","char":"软","word":"软件故障曲线","index":"1-8"},
{"title":"R","char":"软","word":"软件开发模型","index":"2-8"},
{"title":"R","char":"软","word":"软件面临的新挑战","index":"1-11"},
{"title":"R","char":"软","word":"软件模式","index":"5-35"},
{"title":"R","char":"软","word":"软件配置","index":"8-28"},
{"title":"R","char":"软","word":"软件生存周期模型","index":"2-8"},
{"title":"R","char":"软","word":"软件事故","index":"1-18"},
{"title":"R","char":"软","word":"软件实践的问题","index":"1-17"},
{"title":"R","char":"软","word":"软件危机的表现","index":"1-15"},
{"title":"R","char":"软","word":"软件危机的原因","index":"1-20"},
{"title":"R","char":"软","word":"软件误区","index":"1-22"},
{"title":"R","char":"软","word":"软件项目","index":"10-5"},
{"title":"R","char":"软","word":"软件项目计划","index":"10-29"},
{"title":"R","char":"软","word":"软件需求规约","index":"3-14, 3-59"},
{"title":"R","char":"软","word":"软件演化","index":"11-5"},
{"title":"S","char":"色","word":"色彩","index":"7-35"},
{"title":"S","char":"生","word":"生存周期模型","index":"2-8"},
{"title":"S","char":"生","word":"生命周期 测试","index":"9-7"},
{"title":"S","char":"沈","word":"沈备军","index":"每页"},
{"title":"S","char":"涉","word":"涉众定义","index":"3-31"},
{"title":"S","char":"涉","word":"涉众需求","index":"3-14"},
{"title":"S","char":"设","word":"设计","index":"1-42, 1-43"},
{"title":"S","char":"设","word":"设计重用","index":"5-34"},
{"title":"S","char":"设","word":"设计复用","index":"5-34"},
{"title":"S","char":"设","word":"设计工程","index":"5-1"},
{"title":"S","char":"设","word":"设计恢复","index":"11-24"},
{"title":"S","char":"设","word":"设计接口","index":"3-61"},
{"title":"S","char":"设","word":"设计类","index":"6.2-7"},
{"title":"S","char":"设","word":"设计模式","index":"5-7, 5-37, 5-45, 6.2-28"},
{"title":"S","char":"设","word":"设计模型","index":"5-5, 6.2-3"},
{"title":"S","char":"设","word":"设计评审","index":"5-31"},
{"title":"S","char":"设","word":"设计用户界面","index":"3-61"},
{"title":"S","char":"设","word":"设计约束","index":"3-13"},
{"title":"S","char":"设","word":"设计质量","index":"5-29"},
{"title":"S","char":"事","word":"事故","index":"1-18"},
{"title":"S","char":"事","word":"事件流","index":"4.2-41"},
{"title":"S","char":"实","word":"实践的问题","index":"1-17"},
{"title":"S","char":"实","word":"实施 (项目)","index":"10-44"},
{"title":"S","char":"实","word":"实体类","index":"4.2-118, 6.2-72"},
{"title":"S","char":"实","word":"实现视图","index":"6.2-48"},
{"title":"S","char":"时","word":"时间管理","index":"10-9"},
{"title":"S","char":"时","word":"时序图","index":"4.2-133"},
{"title":"S","char":"视","word":"视图","index":"1-64"},
{"title":"S","char":"适","word":"适应性维护","index":"1-51"},
{"title":"S","char":"适","word":"适应系统","index":"5-39"},
{"title":"S","char":"收","word":"收尾 (项目)","index":"10-49"},
{"title":"S","char":"双","word":"双向工程","index":"6.2-87, 8-24"},
{"title":"S","char":"说","word":"说明式语言","index":"8-5"},
{"title":"S","char":"书","word":"书写用例","index":"4.2-42"},
{"title":"S","char":"属","word":"属性表示","index":"6.2-84"},
{"title":"S","char":"数","word":"数据抽象","index":"5-16"},
{"title":"S","char":"数","word":"数据流语言","index":"8-5"},
{"title":"S","char":"数","word":"数据设计","index":"5-6"},
{"title":"S","char":"数","word":"数据视图","index":"6.2-52"},
{"title":"S","char":"术","word":"术语","index":"3-35"},
{"title":"S","char":"术","word":"术语表","index":"3-35"},
{"title":"S","char":"熟","word":"熟练型","index":"7-23"},
{"title":"T","char":"特","word":"特定平台模型","index":"1-66, 2-35"},
{"title":"T","char":"特","word":"特殊需求 (用例)","index":"4.2-53"},
{"title":"T","char":"特","word":"特殊状态","index":"6.2-77"},
{"title":"T","char":"特","word":"特性的优先级","index":"3-57"},
{"title":"T","char":"调","word":"调试","index":"9-3"},
{"title":"T","char":"统","word":"统一软件过程","index":"2-37"},
{"title":"T","char":"通","word":"通信-关联","index":"4.2-37"},
{"title":"T","char":"通","word":"通信图","index":"4.2-136"},
{"title":"T","char":"团","word":"团队结构和分工","index":"10-35"},
{"title":"T","char":"图","word":"图形用户界面","index":"7-15"},
{"title":"W","char":"外","word":"外观模式","index":"5-47"},
{"title":"W","char":"外","word":"外行型","index":"7-23"},
{"title":"W","char":"完","word":"完善性维护","index":"1-51"},
{"title":"W","char":"委","word":"委派","index":"4.2-103"},
{"title":"W","char":"微","word":"微内核","index":"5-39"},
{"title":"W","char":"维","word":"维护","index":"1-49, 11-3"},
{"title":"W","char":"维","word":"维护成本","index":"11-10"},
{"title":"W","char":"维","word":"维护工作量","index":"11-11"},
{"title":"W","char":"维","word":"维护过程","index":"11-14"},
{"title":"W","char":"维","word":"维护类型","index":"1-51, 11-7"},
{"title":"W","char":"维","word":"维护问题","index":"11-9"},
{"title":"W","char":"维","word":"维护无形代价","index":"11-12"},
{"title":"W","char":"维","word":"维护组织结构图","index":"11-13"},
{"title":"W","char":"文","word":"文档化","index":"8-22"},
{"title":"W","char":"文","word":"文档需求","index":"3-55"},
{"title":"W","char":"无","word":"无二义性","index":"3-18"},
{"title":"W","char":"误","word":"误区","index":"1-22"},
{"title":"W","char":"误","word":"误区 (编程)","index":"1-45"},
{"title":"X","char":"详","word":"详细需求","index":"3-50"},
{"title":"X","char":"项","word":"项目","index":"10-5"},
{"title":"X","char":"项","word":"项目成功率","index":"1-16"},
{"title":"X","char":"项","word":"项目的约束","index":"3-33"},
{"title":"X","char":"项","word":"项目范围","index":"3-56"},
{"title":"X","char":"项","word":"项目工作细化结构","index":"10-28"},
{"title":"X","char":"项","word":"项目管理","index":"10-1"},
{"title":"X","char":"项","word":"项目管理知识体系","index":"10-6"},
{"title":"X","char":"项","word":"项目规模","index":"1-12"},
{"title":"X","char":"项","word":"项目估算","index":"10-30"},
{"title":"X","char":"项","word":"项目监控","index":"10-45"},
{"title":"X","char":"项","word":"项目结束","index":"10-49"},
{"title":"X","char":"项","word":"项目经理分级","index":"10-42"},
{"title":"X","char":"项","word":"项目经理技能","index":"10-40"},
{"title":"X","char":"项","word":"项目经理职能","index":"10-41"},
{"title":"X","char":"项","word":"项目前景文档","index":"3-14"},
{"title":"X","char":"项","word":"项目启动","index":"10-13"},
{"title":"X","char":"项","word":"项目实施","index":"10-44"},
{"title":"X","char":"项","word":"项目收尾","index":"10-49"},
{"title":"X","char":"线","word":"线程","index":"6.2-38"},
{"title":"X","char":"线","word":"线性顺序模型","index":"2-10"},
{"title":"X","char":"消","word":"消息","index":"4.2-130"},
{"title":"X","char":"消","word":"消息框","index":"7-4"},
{"title":"X","char":"协","word":"协作","index":"4.2-129"},
{"title":"X","char":"形","word":"形式化方法","index":"1-69"},
{"title":"X","char":"形","word":"形式化方法模型","index":"2-30"},
{"title":"X","char":"性","word":"性能","index":"5-8"},
{"title":"X","char":"性","word":"性能需求","index":"3-11"},
{"title":"X","char":"行","word":"行为建模","index":"4.2-128"},
{"title":"X","char":"信","word":"信息隐藏","index":"5-22"},
{"title":"X","char":"系","word":"系统测试","index":"9-21"},
{"title":"X","char":"系","word":"系统工程","index":"1-40, 3-30"},
{"title":"X","char":"系","word":"系统响应时间","index":"7-27"},
{"title":"X","char":"细","word":"细化需求","index":"3-60"},
{"title":"X","char":"选","word":"选择语言","index":"8-12"},
{"title":"X","char":"需","word":"需求","index":"1-41, 1-42"},
{"title":"X","char":"需","word":"需求变更管理","index":"3-71"},
{"title":"X","char":"需","word":"需求出错","index":"3-22"},
{"title":"X","char":"需","word":"需求的来源","index":"3-38"},
{"title":"X","char":"需","word":"需求定义","index":"3-6, 3-50"},
{"title":"X","char":"需","word":"需求跟踪","index":"3-72"},
{"title":"X","char":"需","word":"需求工程","index":"3-4"},
{"title":"X","char":"需","word":"需求管理","index":"3-70"},
{"title":"X","char":"需","word":"需求获取","index":"3-24, 3-40"},
{"title":"X","char":"需","word":"需求具有的特性","index":"3-17"},
{"title":"X","char":"需","word":"需求评审","index":"3-67"},
{"title":"X","char":"需","word":"需求驱动开发","index":"3-15"},
{"title":"X","char":"需","word":"需求收集","index":"3-39"},
{"title":"X","char":"需","word":"需求验证","index":"3-65"},
{"title":"Y","char":"演","word":"演化型","index":"2-17"},
{"title":"Y","char":"演","word":"演化型类型","index":"2-17"},
{"title":"Y","char":"演","word":"演化性","index":"11-4"},
{"title":"Y","char":"验","word":"验收测试","index":"9-23"},
{"title":"Y","char":"业","word":"业务服务层","index":"6.2-26"},
{"title":"Y","char":"业","word":"业务过程再工程","index":"11-27"},
{"title":"Y","char":"业","word":"业务解决方案","index":"3-27"},
{"title":"Y","char":"应","word":"应用层","index":"6.2-25"},
{"title":"Y","char":"应","word":"应用领域 (语言)","index":"8-6"},
{"title":"Y","char":"硬","word":"硬件故障曲线","index":"1-7"},
{"title":"Y","char":"一","word":"一次性集成测试","index":"9-16"},
{"title":"Y","char":"一","word":"一致性 (界面)","index":"7-10"},
{"title":"Y","char":"依","word":"依赖关系","index":"4.2-108"},
{"title":"Y","char":"异","word":"异常结束","index":"10-50"},
{"title":"Y","char":"易","word":"易用性","index":"5-8"},
{"title":"Y","char":"易","word":"易用性设计 (界面)","index":"7-2"},
{"title":"Y","char":"艺","word":"艺术设计 (界面)","index":"7-2"},
{"title":"Y","char":"泳","word":"泳道","index":"4.2-50"},
{"title":"Y","char":"用","word":"用户分类 (界面)","index":"7-23"},
{"title":"Y","char":"用","word":"用户界面","index":"7-1"},
{"title":"Y","char":"用","word":"用户界面框图","index":"4.2-53"},
{"title":"Y","char":"用","word":"用户界面类","index":"6.2-69"},
{"title":"Y","char":"用","word":"用户界面描述","index":"3-62"},
{"title":"Y","char":"用","word":"用户界面设计","index":"3-61"},
{"title":"Y","char":"用","word":"用例","index":"4.2-29"},
{"title":"Y","char":"用","word":"用例规约","index":"4.2-40"},
{"title":"Y","char":"用","word":"用例建模步骤","index":"4.2-31"},
{"title":"Y","char":"用","word":"用例技术","index":"4.2-29"},
{"title":"Y","char":"用","word":"用例模型组成","index":"4.2-30"},
{"title":"Y","char":"用","word":"用例实现","index":"4.2-116"},
{"title":"Y","char":"用","word":"用例识别","index":"4.2-34"},
{"title":"Y","char":"优","word":"优化类","index":"6.2-68"},
{"title":"Y","char":"有","word":"有效性测试","index":"9-18"},
{"title":"Y","char":"有","word":"有用模型的特征","index":"1-63"},
{"title":"Y","char":"由","word":"由底向上测试","index":"9-16"},
{"title":"Y","char":"源","word":"源程序的文档化","index":"8-22"},
{"title":"Y","char":"约","word":"约束","index":"3-33"},
{"title":"Y","char":"运","word":"运行","index":"1-49"},
{"title":"Y","char":"愚","word":"愚公移山","index":"10-4"},
{"title":"Y","char":"浴","word":"浴缸曲线","index":"1-7"},
{"title":"Y","char":"语","word":"语言选择","index":"8-12"},
{"title":"Y","char":"预","word":"预防性维护","index":"1-51"},
{"title":"Z","char":"再","word":"再工程","index":"11-25"},
{"title":"Z","char":"再","word":"再工程过程","index":"11-29"},
{"title":"Z","char":"增","word":"增量型","index":"2-14"},
{"title":"Z","char":"战","word":"战略性学科","index":"1-33"},
{"title":"Z","char":"正","word":"正常结束","index":"10-50"},
{"title":"Z","char":"正","word":"正向工程","index":"6.2-87, 8-24"},
{"title":"Z","char":"支","word":"支持计划","index":"10-27"},
{"title":"Z","char":"支","word":"支持性","index":"3-10"},
{"title":"Z","char":"知","word":"知识体系","index":"1-37"},
{"title":"Z","char":"质","word":"质量","index":"5-29"},
{"title":"Z","char":"质","word":"质量范围","index":"3-54"},
{"title":"Z","char":"质","word":"质量管理","index":"10-9"},
{"title":"Z","char":"质","word":"质量因素","index":"5-8"},
{"title":"Z","char":"中","word":"中国的软件产业现状","index":"1-19"},
{"title":"Z","char":"终","word":"终止测试","index":"9-45"},
{"title":"Z","char":"状","word":"状态","index":"6.2-75"},
{"title":"Z","char":"状","word":"状态机图","index":"6.2-76"},
{"title":"Z","char":"专","word":"专家型","index":"7-23"},
{"title":"Z","char":"专","word":"专用过程模型","index":"2-27"},
{"title":"Z","char":"主","word":"主程序员小组","index":"10-38"},
{"title":"Z","char":"逐","word":"逐步求精","index":"5-18"},
{"title":"Z","char":"子","word":"子系统","index":"6.2-9"},
{"title":"Z","char":"子","word":"子系统接口","index":"6.2-63"},
{"title":"Z","char":"子","word":"子系统设计","index":"6.2-65"},
{"title":"Z","char":"字","word":"字符用户界面","index":"7-14"},
{"title":"Z","char":"自","word":"自顶向下测试","index":"9-16"},
{"title":"Z","char":"自","word":"自动化测试","index":"9-7"},
{"title":"Z","char":"自","word":"自主研发的立项管理","index":"10-17"},
{"title":"Z","char":"资","word":"资产检查","index":"10-51"},
{"title":"Z","char":"总","word":"总结经验教训","index":"10-51"},
{"title":"Z","char":"综","word":"综合管理","index":"10-7"},
{"title":"Z","char":"综","word":"综合评估","index":"10-51"},
{"title":"Z","char":"最","word":"最广泛的模型","index":"2-19"},
{"title":"Z","char":"最","word":"最终状态","index":"6.2-77"},
{"title":"Z","char":"作","word":"作用点","index":"2-4"}
]